--- 
after_success: 
  - "bash <(curl -s https://codecov.io/bash)"
before_install: "cd Proyecto"
dist: xenial
jdk: 
  - openjdk7
  - openjdk8
language: java
script: 
  - "mvn clean package"
  - "mvn cobertura:cobertura"
sudo: false