#Usa lenguaje Java
language: java
#Usa OpenJDK 8
jdk: 
  - openjdk8
#Usa la distro xenial
dist: trusty
#No hacer el proceso con sudo
sudo: false
#Le indicamos que usaremos mongo
services:
  - mongodb
#Script a realizar
#Limpia los archivos de builds anteriores y reempaqueta
#Despues corre los test de cobertura
script: 
  - "cd ./Mesas && mvn clean package cobertura:cobertura"
  - "bash <(curl -s https://codecov.io/bash)"
  - "cd .."
  - "cd ./Cocina && mvn clean package cobertura:cobertura"
  - "bash <(curl -s https://codecov.io/bash)"
  - "cd .."
  - "cd ./Camarero && mvn clean package cobertura:cobertura"
  - "bash <(curl -s https://codecov.io/bash)"
  - "cd .."
  - "cd ./APIService && mvn clean package cobertura:cobertura"
  - "bash <(curl -s https://codecov.io/bash)"
