name: Java CI
#Los test se pasaran al realizar un push
on: [push]

jobs:
  build:
    #Correran en la última distro de ubuntu
    runs-on: ubuntu-latest
    strategy:
      #Se haran 8 en paralelo
      max-parallel: 8
      matrix:
        #Se testearan las siguientes versiones de Open JDK
        JDK: [6,7,8,9,10,11,12,13]

    steps:
      # Usamos la action checkout@1
    - uses: actions/checkout@v1
      #Decimos la versión del JDK que vamos a usar
    - name: Set up JDK ${{ matrix.JDK }}
      #usamos la action setup-java@v1
      uses: actions/setup-java@v1
      with:
        #le decimos la versión del java que usará
        java-version: ${{ matrix.JDK }}
    - name: Build with Maven
      #Empaqueta con maven y corre los tests unitarios y de cobertura
      run: |
          cd Proyecto
          mvn clean package
          mvn cobertura:cobertura
