name: Java CI

on: [push]

jobs:
  build:
    strategy:
      
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        JDK: [7,8]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.JDK }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.JDK }}
    - name: Build with Maven
      run: |
       cd ./Proyecto;
       mvn clean package --file pom.xml;
       mvn cobertura:cobertura --file pom.xml;
