name: Java CI
#Cuando se haga un push
on: [push]

jobs:
  build:
    strategy:
      matrix:
        #Para las últimas version de Ubuntu
        platform: [ubuntu-latest]
        #Para las versiones del JDK 8
        JDK: [8]
        #Para las versiones de mongo
        mongodb-version: ["4.2"]
    
    #Corre en todas las plataformas de la matriz
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v1
    #Le indicamos el nombre del paso
    - name: Set up JDK ${{ matrix.JDK }}
      uses: actions/setup-java@v1
      with:
        #Corre en todos los JDK quele hemos indicado
        java-version: ${{ matrix.JDK }}
    - name: Launch MongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: ${{ matrix.mongodb-version }}
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
          HOST: ${{ secrets.HOST }}
          HOST_MESAS: ${{ secrets.HOST_MESAS }}
          HOST_COCINA: ${{ secrets.HOST_COCINA }}
          HOST_CAMARERO: ${{ secrets.HOST_CAMARERO }}
          DEFAULT_DB_PORT: ${{ secrets. DEFAULT_DB_PORT }}
          HOST_LOCAL_NAME: ${{ secrets.HOST_LOCAL_NAME }}
          MESAS_DB_NAME: ${{ secrets.MESAS_DB_NAME }}
          COCINA_DB_NAME: ${{ secrets.COCINA_DB_NAME }}
          CAMARERO_DB_NAME: ${{ secrets.CAMARERO_DB_NAME }}
          HOST_API_PORT: ${{ secrets.HOST_API_PORT}}
          HOST_MESAS_PORT: ${{ secrets.HOST_MESAS_PORT}}
          HOST_CAMARERO_PORT: ${{ secrets.HOST_CAMARERO_PORT}}
          HOST_COCINA_PORT: ${{ secrets.HOST_COCINA_PORT}}
      #Le indicamos el nombre del paso
    - name: Build with Maven
      #Va a proyecto
      #Limpia los archivos de builds antiguas y lo empaqueta de nuevo instalando las dependencias.
      #Se corren los tests
      #Se corren los test de covertura
      run: |
       make install
       java -jar ./Cocina/target/RestauranProjectCocina-0.0.1-SNAPSHOT.jar &
       cd ./Mesas
       mvn cobertura:cobertura 
       kill -9 $(sudo lsof -t -i:8081)
       cd ..
       java -jar ./Camarero/target/RestauranProjectCamarero-0.0.1-SNAPSHOT.jar &
       cd ./Cocina
       mvn cobertura:cobertura 
       kill -9 $(sudo lsof -t -i:8082)
       cd ..
       cd ./Camarero
       mvn cobertura:cobertura 
       cd ..
       java -jar ./Mesas/target/RestauranProject-0.0.1-SNAPSHOT.jar &
       java -jar ./Cocina/target/RestauranProjectCocina-0.0.1-SNAPSHOT.jar &
       java -jar ./Camarero/target/RestauranProjectCamarero-0.0.1-SNAPSHOT.jar &
       cd ./APIService
       mvn cobertura:cobertura 
